// Mock file - will be auto-generated by Convex when you run `npx convex dev`
import type { GenericId } from "convex/values";

export type TableNames = string;

export type DataModel = Record<string, any>;
